[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "diamond_square"
version = "0.1.8"
description = "A package which can implement and draw terrains using the diamond square algorithm in pgzero and pygame. Uses C for fast rendering."
readme = "README.md"
requires-python = ">=3.5"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
authors = [
  { name="Gautam Pulugurta", email="gootyboy@gmail.com" },
]
dependencies = [
    "pgzero",
    "pillow",
    "pygame",
]

[project.urls]
Homepage = "https://github.com/gootyboy/diamond_square"
Issues = "https://github.com/gootyboy/diamond_square/issues"

[tool.hatch.build.targets.sdist]
exclude = ["/venv"]

[tool.hatch.build.targets.wheel]
exclude = ["/venv"]
