[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "diamond_square"
version = "1.0.0"
description = "A package which can draw terrains and interactive terrains using the Diamond Square Algorithm in pgzero and pygame. Also include 3d terrains in panda3d. Uses C for fast rendering."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
authors = [
  { name="Gautam Pulugurta", email="gootyboy@gmail.com" },
]
dependencies = [
    "pgzero",
    "pillow",
    "pygame",
    "panda3d"
]

[project.urls]
Homepage = "https://github.com/gootyboy/diamond_square"
Issues = "https://github.com/gootyboy/diamond_square/issues"

[tool.hatch.build.targets.sdist]
exclude = ["/venv"]

[tool.hatch.build.targets.wheel]
exclude = ["/venv"]
